### ISSUE TITLE
Упростить проверки моков для тестов 

### ISSUE THREAD

**Issue by vasiliev-alexey** [alexanderpono/ponomarenko-alex-otus#45]
Упростить проверки моков для тестов 
например
``` js
 expect(mockCallBack.mock.calls.length).toEqual(1);
```
 
Можно переписать в упрощенном варианте 
``` js
   expect(mockCallBack).toHaveBeenCalledTimes(1);
```
   
   
Ну и в целом код однотипный - можно подумать не  переделку у табличные тесты test.each

**Comment by alexanderpono** [comment]
Исправлено в https://github.com/alexanderpono/ponomarenko-alex-otus/pull/58
