### ISSUE TITLE
Ввод пробела вместо имени

### ISSUE THREAD

**Issue by artem-volirvag** [alexanderpono/ponomarenko-alex-otus#46]
Допускает ввод одного пробела вместо имени. Возможно, это неправильно

**Comment by alexanderpono** [comment]
Исправлено в https://github.com/alexanderpono/ponomarenko-alex-otus/pull/58 .

Результат исправления можно посмотреть по ссылке:
https://alexanderpono.github.io/ponomarenko-alex-otus/react-2021-09/hw13/application/#/login

Для входя в симулятор нужно ввести имя пользователя. Если вводить пробелы в поле имени пользователя - кнопка "Start" остается неактивной. Для ее активации - необходимо ввести в поле отображаемые символы.
