### ISSUE TITLE
Нет информации о статусе игры

### ISSUE THREAD

**Issue by ermakof** [alexanderpono/ponomarenko-alex-otus#49]
Не очень понятен статус игры
Клетки быстро исчезли и поле остается пустым и непонятно что дальше делать
Нужно либо вывести какой-либо таймер, либо выводить геймовер, если игра конечна, либо таймер обратного отсчета, все что угодно, но чтобы было понятно что происходит (или не происходит) с игровым полем.

**Comment by alexanderpono** [comment]
Исправлено в https://github.com/alexanderpono/ponomarenko-alex-otus/pull/58
Результат исправления можно посмотреть по ссылке: 
https://alexanderpono.github.io/ponomarenko-alex-otus/react-2021-09/hw13/application/#/login

Для входя в симулятор нужно ввести имя пользователя. В авторизованной зоне в шапке приложения появилась надпись "Generation: [число]"
