### ISSUE TITLE
Не все правила Game of life реализованы?

### ISSUE THREAD

**Issue by centralToNowhere** [alexanderpono/ponomarenko-alex-otus#62]
Действия для воспроизведения:

1. Перейти https://alexanderpono.github.io/ponomarenko-alex-otus/react-2021-09/hw13/application/#/login
2. Ввести имя пользователя
3. Выделить ячейки, как на скриншоте:

![gol-test](https://user-images.githubusercontent.com/18603013/155948470-4ecec2ef-1e90-4fcc-a686-32d5f080c4fa.png)
4. Нажать кнопку play

Ожидаемое поведение: По правилам GOL, в пустой клетке, рядом с которой ровно три живые клетки, зарождается жизнь, 
https://ru.wikipedia.org/wiki/%D0%98%D0%B3%D1%80%D0%B0_%C2%AB%D0%96%D0%B8%D0%B7%D0%BD%D1%8C%C2%BB
т е следующее поколение должно быть таким:
![gol-test2](https://user-images.githubusercontent.com/18603013/155949010-8b25a6dd-8c16-4bb5-aec6-31cf39c5169f.png)

Фактическое поведение:
Все клетки "мертвы"

**Comment by alexanderpono** [comment]
Спасибо, исправляю в https://github.com/alexanderpono/ponomarenko-alex-otus/pull/65
